environment = "dev"
region = "us-east-2"
s3_bucket = "sera-s3-bucket-de1"           #Will be used to set backend.tf
s3_folder_project = "application"            #Will be used to set backend.tf
s3_folder_region = "us-east-1"               #Will be used to set backend.tf
s3_folder_type = "state"                     #Will be used to set backend.tf
s3_tfstate_file = "infrastructure.tfstate"   #Will be used to set backend.tf
vpc_id = "vpc-67dd1f1f"
subnet1 = "subnet-250e515c"
subnet2 = "subnet-d9a0d992"
subnet3 = "subnet-a33d13f9"
cluster_name = "dev-cluster"
instance_type = "t2.micro"
asg_max_size = "10" 
asg_min_size = "3"
asg_desired_capacity = "3"
cluster_version = "1.14"