environment = "dev"
region = "us-east-2"
s3_bucket = "sera-s3-bucket-de1"           #Will be used to set backend.tf
s3_folder_project = "application"            #Will be used to set backend.tf
s3_folder_region = "us-east-1"               #Will be used to set backend.tf
s3_folder_type = "state"                     #Will be used to set backend.tf
s3_tfstate_file = "infrastructure.tfstate"   #Will be used to set backend.tf
vpc_id = "vpc-00792ef88db6b0822"
subnet1 = "subnet-08bca1cfabdbbb1dd"
subnet2 = "subnet-094e0f1ff04a19356"
subnet3 = "subnet-0e90798ae550c7bb2"
cluster_name = "dev-cluster"
instance_type = "t2.micro"
asg_max_size = "10" 
asg_min_size = "3"
asg_desired_capacity = "3"
cluster_version = "1.14"